services:
    db:
        container_name: db
        image: mirror.gcr.io/postgres:${POSTGRES_VERSION:-16}-alpine
        volumes:
            - postgres_data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_DB: ${POSTGRES_DB:-postgres}
        ports:
            - "54321:5432"

    db_test:
        container_name: db_test
        image: mirror.gcr.io/postgres:${POSTGRES_VERSION:-16}-alpine
        volumes:
            - postgres_test_data:/var/lib/postgresql/data:rw
        environment:
            POSTGRES_PASSWORD: test
            POSTGRES_USER: test
            POSTGRES_DB: db_test
        ports:
            - "5433:5432"

    php:
        container_name: php
        build:
            context: .
            dockerfile: docker/app/Dockerfile
            args:
                UID: ${UID}
                GID: ${GID}
        command: [ 'php-fpm', '--nodaemonize' ]
        depends_on:
            - db
        working_dir: /var/www/app
        extra_hosts:
            - host.docker.internal:host-gateway
        volumes:
            - ./:/var/www/app
        environment:
            UID: ${UID:-1000}
            GID: ${GID:-1001}
            CORS_ALLOW_ORIGIN: '*'

    back-nginx:
        container_name: back-nginx
        image: mirror.gcr.io/nginx:1.27-alpine
        restart: always
        volumes:
            - ./docker/nginx/local/default.conf:/etc/nginx/conf.d/default.conf
            - ./:/var/www/app
        depends_on:
            - php
        ports:
            - "81:80"


volumes:
    postgres_data:
    postgres_test_data:
